- hosts: slurm_compute
  remote_user: root
  become: true
  # become_method: sudo
  # become_flag: sudo
  gather_facts: false
  vars_files:
    - "../vars/{{ env }}.yml"

  tasks:
    - name: copy_slurm_conf
      copy:
        src: "{{CONFIG_PATH}}{{SLURM_CONF}}"
        dest: /etc/slurm/

    - name: copy_cgroup_conf
      copy:
        src: "{{CONFIG_PATH}}{{CGROUP_CONF}}"
        dest: /etc/slurm/

    - name: copy_job_submit
      copy:
        src: "{{CONFIG_PATH}}{{JOB_SUBMIT}}"
        dest: /etc/slurm/

    - name: make_spool_slurm
      file:
        path: /var/spool/kbds-slurm
        state: directory
        # mode: 0755
        # owner: slurm
        # group: slurm

    - name: make_log_slurm
      file:
        path: /var/log/kbds-slurm
        state: directory
        # mode: 0755
        # owner: slurm
        # group: slurm

    - name: set_log
      shell: |
        chown slurm: /var/spool/kbds-slurm
        chmod 755 /var/spool/kbds-slurm
        touch /var/log/kbds-slurm/slurmd.log
        chown slurm: /var/log/kbds-slurm/slurmd.log

    - name: set_firewall
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes
